name: petsc

channels:
        - defaults
        - conda-forge

dependencies:
            - python=3.6
            - netcdf4
            - matplotlib
            - snakeviz
            - conda-forge::petsc4py
