#!/bin/csh
#PBS -q parallel8
#PBS -l select=1:ncpus=8:mpiprocs=8
#PBS -l walltime=00:15:00

# cd to the directory you submitted your job
cd $PBS_O_WORKDIR

# get the path for mpirun
setenv PATH ${HOME}/miniconda2/envs/petsc/bin:${PATH}
setenv PYTHONPATH $PBS_O_WORKDIR/..
mpirun -np 8 python test_basic.py -mf -ksp_view -ksp_monitor -ksp_converged_reason >& output.mpi

